#!/usr/bin/env python3
"""Build firmware/lib/display/ui/WeatherIcons.hpp from Assets/weather_assets/.

Every icon gets the same treatment so the set looks consistent on HOME:
trim transparent borders -> centre on a 30:32 canvas -> resize to 30x32
(Lanczos) -> RGB565 with magenta 0xF81F as the transparent colour key
(alpha <= 127), the format draw_sprite_transparent() expects.

    python scripts/make_weather_icons.py

Requires Pillow. Paths are relative to the repo root. Assets/ is not in git
(art sources stay local), so run this on a machine that has them.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "Assets" / "weather_assets"
OUT = ROOT / "firmware" / "lib" / "display" / "ui" / "WeatherIcons.hpp"
W, H = 30, 32
KEY = 0xF81F

# (C array name, source file)
ICONS = [
    ("image_weather_sunny_bits",        "sun.png"),
    ("image_weather_partly_sunny_bits", "partly_sunny.png"),
    ("image_weather_cloud_bits",        "cloud.png"),
    ("image_weather_rain_bits",         "rain.png"),
    ("image_weather_thunder_bits",      "thunderstorm.png"),
]


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(path):
    im = Image.open(path).convert("RGBA")
    box = im.getbbox()
    if box:
        im = im.crop(box)
    w, h = im.size
    cw, ch = max(w, round(h * W / H)), max(h, round(w * H / W))
    canvas = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    canvas.paste(im, ((cw - w) // 2, (ch - h) // 2))
    icon = canvas.resize((W, H), Image.LANCZOS)
    out = []
    raw = icon.tobytes()
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]
        if a <= 127:
            out.append(KEY)
        else:
            v = rgb565(r, g, b)
            out.append(v if v != KEY else KEY ^ 1)   # never collide with the key
    return out


def main():
    lines = [
        "#pragma once",
        f"// Home weather icons: full-color RGB565 sprites, {W}x{H}, magenta 0x{KEY:04X} color-key",
        "// for transparency (alpha<=127 at convert time). Generated by",
        "// scripts/make_weather_icons.py from Assets/weather_assets/"
        "{sun,partly_sunny,cloud,rain,thunderstorm}.png",
        "// (trimmed, centred, Lanczos-resized). Do not hand-edit; regenerate via the script.",
        "#include <cstdint>",
        "namespace Fuchey {",
        "",
        f"static constexpr int kWeatherIconW = {W};",
        f"static constexpr int kWeatherIconH = {H};",
        f"static constexpr uint16_t kWeatherTransparent = 0x{KEY:04X};",
        "",
    ]
    for name, file in ICONS:
        px = convert(SRC / file)
        lines.append(f"// {file}")
        lines.append(f"static const uint16_t {name}[] = {{")
        for i in range(0, len(px), 8):
            lines.append("    " + ", ".join(f"0x{v:04X}" for v in px[i:i + 8]) + ",")
        lines.append("};")
        lines.append("")
    lines.append("} // namespace Fuchey")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(ICONS)} icons)")


if __name__ == "__main__":
    main()
