#!/usr/bin/env python3
"""Convert a TTF into an Adafruit-GFX-compatible C header (Fuchey format).

Renders ASCII 0x20..0x7E with Pillow, packs 1-bpp MSB-first exactly like
Adafruit's fontconvert (continuous bit stream per glyph, no row padding),
and emits Fuchey-namespace arrays: <Name>Bitmaps / <Name>Glyphs / <Name>.

Pixel size auto-calibrates to a 13px cap height (matches FreeSansBold9pt7b)
unless --px is given.

Usage:
    python scripts/ttf_to_gfx.py <font.ttf> <SymbolName> <out.hpp> [--px N] [--yadv N]
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x7E
TARGET_CAP = 13


def render_glyph(font, ch):
    """Returns (xAdvance, w, h, xOffset, yOffset, bits MSB-first)."""
    img = Image.new("L", (120, 120), 0)
    d = ImageDraw.Draw(img)
    bx, by = 30, 80
    d.text((bx, by), ch, font=font, anchor="ls", fill=255)
    adv = int(round(font.getlength(ch)))
    bb = img.getbbox()
    if not bb:
        return adv, 0, 0, 0, 0, []
    x0, y0, x1, y1 = bb
    w, h = x1 - x0, y1 - y0
    bits = [1 if img.getpixel((x, y)) >= 128 else 0
            for y in range(y0, y1) for x in range(x0, x1)]
    return adv, w, h, x0 - bx, y0 - by, bits


def main() -> None:
    args = sys.argv[1:]
    if len(args) < 3:
        sys.exit(__doc__)
    ttf, name, out = args[0], args[1], args[2]
    px = 0
    yadv = 22
    for i, a in enumerate(args):
        if a == "--px" and i + 1 < len(args):
            px = int(args[i + 1])
        if a == "--yadv" and i + 1 < len(args):
            yadv = int(args[i + 1])

    if px <= 0:
        probe = ImageFont.truetype(ttf, 20)
        _, _, cap_h, _, _, _ = render_glyph(probe, "H")
        px = max(8, round(20 * TARGET_CAP / max(cap_h, 1)))
    font = ImageFont.truetype(ttf, px)

    glyphs = []
    for code in range(FIRST, LAST + 1):
        adv, w, h, xo, yo, bits = render_glyph(font, chr(code))
        glyphs.append((code, chr(code), adv, w, h, xo, yo, bits))

    blob = bytearray()
    rows = []
    for code, ch, adv, w, h, xo, yo, bits in glyphs:
        rows.append((code, ch, len(blob), adv, w, h, xo, yo))
        acc, n = 0, 0
        for b in bits:
            acc = (acc << 1) | b
            n += 1
            if n == 8:
                blob.append(acc)
                acc, n = 0, 0
        if n:
            blob.append(acc << (8 - n))

    L = []
    L.append("#pragma once")
    L.append(f"// Auto-generated by scripts/ttf_to_gfx.py from '{Path(ttf).name}'.")
    L.append(f"// ASCII 0x20..0x7E, {len(blob)} bytes bitmap. Do not hand-edit.")
    L.append("#include <cstdint>")
    L.append("namespace Fuchey {")
    L.append("")
    L.append(f"static const uint8_t {name}Bitmaps[] = {{")
    for i in range(0, len(blob), 12):
        L.append("    " + ", ".join(f"0x{v:02X}" for v in blob[i:i + 12]) + ",")
    L.append("};")
    L.append("")
    L.append(f"static const GFXglyph {name}Glyphs[] = {{")
    for code, ch, off, adv, w, h, xo, yo in rows:
        safe = ch if ch not in ("\\", "'") else "?"
        L.append(f"    {{{off}, {w}, {h}, {adv}, {xo}, {yo}}},  // 0x{code:02X} '{safe}'")
    L.append("};")
    L.append("")
    L.append(f"static const GFXfont {name} = {{{name}Bitmaps,")
    L.append(f"                                 {name}Glyphs,")
    L.append(f"                                 0x{FIRST:02X}, 0x{LAST:02X}, {yadv}}};")
    L.append("")
    L.append("} // namespace Fuchey")
    Path(out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"{name}: px={px} yadv={yadv} bitmap={len(blob)} bytes -> {out}")


if __name__ == "__main__":
    main()
